# Generated by Django 3.1.12 on 2022-12-20 16:28

import carriers.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carriers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('reporting_structure', djongo.models.fields.ArrayField(model_container=carriers.models.ReportingStructure)),
            ],
        ),
    ]
